/**
 * Writes `dist/sw.js` with a precache list built from what actually shipped.
 *
 * ## Why this is a build step and not a hand-written list
 *
 * Vite hashes every asset name (`worker-BdZ2-Yn1.js`, `index-24UO2SWA.js`), so a
 * hand-written precache list is wrong the moment anything changes — and wrong
 * *silently*, because a stale URL in `caches.match` is a cache miss, not an error.
 * The app would install, go offline, and serve nothing.
 *
 * So the list is derived from the directory that was just written. The one thing
 * that can go wrong is the two being out of step, and that is covered by
 * `verify-sw.mjs`-style assertions in the same file: the emitted list has to be
 * non-empty and has to contain the entry HTML.
 *
 * ## Why there is a cache at all, and what it deliberately does NOT do
 *
 * A PWA that is not offline-capable is a PWA in name only: `AGENTS.md` §2a makes
 * "installierbar **und offline lauffähig**" part of the target. But the precache is
 * the *shell* only. It never caches a provider response, never caches a
 * `webfetch` target, and never touches a cross-origin request at all — those go
 * straight to the network, which is the only correct behaviour for an LLM stream
 * and for fetching someone's file. `AGENTS.md` §2's "kein Server" would be violated
 * by a cache that pretended to be one.
 *
 * Run: `node scripts/build-sw.mjs` (wired into the build).
 */

import { readdirSync, statSync, writeFileSync } from "node:fs";
import { join, relative, resolve, sep } from "node:path";

/**
 * The dist directory, as `--dist <path>` — so this can be tested against a
 * synthetic tree. Verified only against a real build it is untestable: it needs a
 * finished build, and a finished build needs a green typecheck, and a green
 * typecheck is exactly what a parallel agent can take away for an hour.
 *
 * **An explicit flag, not a positional argument, and that is a bug I shipped.**
 * The first version read `process.argv[2]`. This script is chained at the end of
 * `build`, and the Playwright web server calls `pnpm … build --mode e2e` — pnpm
 * appends pass-through arguments to the **end** of the script, so `argv[2]` was
 * `"--mode"` and the script died with `scandir("--mode")`. `pnpm e2e` could not
 * start at all, and it failed at a place with no relation to what it was testing.
 *
 * The lesson is the shape, not the typo: **a positional argument in an npm-script
 * chain is not yours.** Anything after the script name belongs to whoever appended
 * it.
 */
function parseDist(argv) {
  const flag = argv.indexOf("--dist");
  if (flag !== -1 && argv[flag + 1] !== undefined) return resolve(process.cwd(), argv[flag + 1]);
  const inline = argv.find((a) => a.startsWith("--dist="));
  if (inline !== undefined) return resolve(process.cwd(), inline.slice("--dist=".length));
  return resolve(process.cwd(), "packages/baah-web/dist");
}

const DIST = parseDist(process.argv.slice(2));

const COLLECTED_EXTENSIONS = new Set([
  ".js",
  ".css",
  ".html",
  ".wasm",
  ".webmanifest",
  ".png",
  ".svg",
  ".woff2",
]);

/** Every precachable file in `dist/`, as site-absolute paths. */
function collect() {
  const found = [];
  const walk = (directory) => {
    for (const entry of readdirSync(directory).sort()) {
      const full = join(directory, entry);
      if (statSync(full).isDirectory()) {
        walk(full);
        continue;
      }
      if (entry === "sw.js") continue; // never precache the worker into itself
      const rel = `/${relative(DIST, full).split(sep).join("/")}`;
      const extension = rel.slice(rel.lastIndexOf("."));
      if (!COLLECTED_EXTENSIONS.has(extension)) continue;
      found.push(rel);
    }
  };
  walk(DIST);
  return found;
}

const assets = collect();

if (assets.length === 0) {
  process.stderr.write("build-sw: dist/ is empty or missing — did the build run?\n");
  process.exit(1);
}
if (!assets.includes("/index.html")) {
  process.stderr.write(
    "build-sw: /index.html is not in dist/, so the precache would have nothing to serve offline.\n",
  );
  process.exit(1);
}

const version = process.env.BUILD_ID ?? "dev";
const list = JSON.stringify(assets);

writeFileSync(
  join(DIST, "sw.js"),
  `/**
 * baah service worker — GENERATED by scripts/build-sw.mjs. Do not edit.
 * Precache: ${assets.length} files, build "${version}".
 */
const CACHE = "baah-${version}";
const PRECACHE = ${list};

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      // addAll is atomic: one failure fails the whole install, which is the
      // behaviour we want. A cache that silently misses one asset is the
      // offline-mode-that-lies.
      .then((cache) => cache.addAll(PRECACHE))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  // Same-origin GET only. Everything else - the LLM provider, a \`webfetch\` target,
  // a CORS probe - goes straight to the network. Caching a model response would be
  // both wrong and a privacy statement we cannot make.
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  event.respondWith(
    caches.match(request).then((hit) => {
      if (hit !== undefined) {
        // Cache-first for the shell, which is precache-complete and content-hashed,
        // so a stale hit is impossible: a changed file is a changed name.
        return hit;
      }
      return fetch(request)
        .then((response) => {
          if (response.ok && PRECACHE.includes(url.pathname)) {
            const copy = response.clone();
            caches.open(CACHE).then((cache) => cache.put(request, copy));
          }
          return response;
        })
        .catch(() => caches.match("/index.html"));
    }),
  );
});
`,
  "utf8",
);

process.stdout.write(`build-sw: dist/sw.js precaches ${assets.length} files\n`);
for (const asset of assets) process.stdout.write(`build-sw:   ${asset}\n`);